
function Start-AutodeskPopupSlapdown(){
    # launches an autohotkey script that watches for, and slaps down, a variety of annoying 
    # modal pop-ups that interfere with using Revit and AutoCAD.
    # requires autohoteky to be installed and associated with .ahk files.

    $pathOfPopupSlapdownScriptFile = join-path $env:temp "popup_slapdown--79092a45f12943e2aae8dff20cabb7b3.ahk"
    $pathOfTemporarySlapdownLogDirectory = "$(resolve-path $env:temp)"
    $popupSlapdownScriptContent = (
        @(
            "#SingleInstance, Force                                                                                                                                "
            "#Persistent                                                                                                                                           "
            "SetWorkingDir, %A_ScriptDir%                                                                                                                          "
            "logFile:=`"$($pathOfTemporarySlapdownLogDirectory)/`" . A_ScriptName . `".log`"                                                                       "
            "writeToLog(`"starting`")                                                                                                                              "
            "                                                                                                                                                      "
            "Menu, Tray, Insert, ,view the log, viewTheLog                                                                                                         "
            "                                                                                                                                                      "
            "SetTitleMatchMode RegEx                                                                                                                               "
            "                                                                                                                                                      "
            "                                                                                                                                                      "
            "; define the criteria for the various user-interface modal (i.e. requiring user intervention before resuming the program)                             "
            "; windows that acad throws up to block our progress.                                                                                                  "
            "                                                                                                                                                      "
            "GroupAdd, lostSheetSetAssociationWindowDefinition           ,Sheet Set Manager - Lost Set Association ahk_exe acad.exe                                "
            "GroupAdd, fatalError1WindowDefinition                       ,AutoCAD Error Aborting,FATAL ERROR:                                                      "
            "GroupAdd, fatalError2WindowDefinition                       ,AutoCAD Alert,AutoCAD cannot continue                                                    "
            "GroupAdd, projectwiseSavePromptWindowDefinition             ,ProjectWise,Save changes to Drawing1.dwg                                                 "
            "GroupAdd, drawingFileNotValidWindowDefinition               ,AutoCAD Message ahk_exe acad.exe,Drawing file is not valid.                              "
            "; GroupAdd, openDrawingErrorsFoundWindowDefinition          ,Open Drawing - Errors Found,Would you like to cancel this open                           "
            "GroupAdd, openDrawingErrorsFoundWindowDefinition            ,Open Drawing - Errors Found                                                              "
            "GroupAdd, trialPromptWindowDefinition                       ,IE WebBrowser ahk_exe AdskLicensingAgent.exe                                             "
            "GroupAdd, drawingNotBelongToCurrentProjectWindowDefinition  ,Drawing does Not Belong to the Current Project ahk_exe acad.exe                          "
            "GroupAdd, drawingRecoveryWindowDefinition                   ,Drawing Recovery ahk_exe acad.exe                                                        "
            "GroupAdd, revitInvalidSignatureWindowDefinition             ,Security - Invalid Signature ahk_exe Revit.exe                                           "
            "GroupAdd, revitUnsignedAddinWindowDefinition                ,Security - Unsigned Add-In ahk_exe Revit.exe                                             "
            "GroupAdd, revitErrorReportWindowDefinition                  ,Revit .*Error Report ahk_exe senddmp.exe                                                 "
            "GroupAdd, revitErrorReportCancelledWindowDefinition         ,Error Report - Cancelled ahk_exe senddmp.exe                                             "
            "GroupAdd, acadErrorReportWindowDefinition                   ,AutoCAD .*Error Report ahk_exe senddmp.exe                                               "
            "GroupAdd, acadSaveDrawing1WindowDefinition                  ,AutoCAD ahk_exe acad.exe,Save changes to Drawing1\.dwg\?                                 "
            "GroupAdd, fusion360ErrorReportWindowDefinition              ,Fusion 360 .*Error Report ahk_exe senddmp.exe                                               "
            "                                                                                                                                                      "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group lostSheetSetAssociationWindowDefinition                                                  "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group fatalError1WindowDefinition                                                              "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group fatalError2WindowDefinition                                                              "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group projectwiseSavePromptWindowDefinition                                                    "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group drawingFileNotValidWindowDefinition                                                      "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group openDrawingErrorsFoundWindowDefinition                                                   "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group trialPromptWindowDefinition                                                              "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group drawingNotBelongToCurrentProjectWindowDefinition                                         "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group drawingRecoveryWindowDefinition                                                          "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group revitInvalidSignatureWindowDefinition                                                    "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group revitUnsignedAddinWindowDefinition                                                       "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group revitErrorReportWindowDefinition                                                         "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group revitErrorReportCancelledWindowDefinition                                                "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group acadErrorReportWindowDefinition                                                          "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group acadSaveDrawing1WindowDefinition                                                         "
            "GroupAdd, anyPopupWindowDefinition                ,ahk_group fusion360ErrorReportWindowDefinition                                                         "
            "                                                                                                                                                      "
            "                                                                                                                                                      "
            "                                                                                                                                                      "
            "Loop{                                                                                                                                                 "
            "    WinWait, ahk_group anyPopupWindowDefinition                                                                                                       "
            "    ; writeToLog(`"encountered a halting popup window that we will attempt to slap down.`")                                                           "
            "    ; might consider logging some of the window porperties or window text, etc.                                                                       "
            "    WinGet,idOfOffendingWindow,                                                                                                                       "
            "    WinGet,processNameOfOffendingWindow,ProcessName,ahk_id %idOfOffendingWindow%                                                                      "
            "    writeToLog(`"idOfOffendingWindow: `" . idOfOffendingWindow)                                                                                       "
            "    writeToLog(`"processNameOfOffendingWindow: `" . processNameOfOffendingWindow)                                                                     "
            "                                                                                                                                                      "
            "    if WinExist(`"ahk_group lostSheetSetAssociationWindowDefinition`"){                                                                               "
            "        writeToLog(`"slapping down sheetset association error`")                                                                                      "
            "        ControlClick,Ignore the lost association,                                                                                                     "
            "    } else if WinExist(`"ahk_group fatalError1WindowDefinition`") {                                                                                   "
            "        writeToLog(`"slapping down fatal error popup 1`")                                                                                             "
            "        ControlSend, , {Enter}                                                                                                                        "
            "    } else if WinExist(`"ahk_group fatalError2WindowDefinition`") {                                                                                   "
            "        writeToLog(`"slapping down fatal error popup 2`")                                                                                             "
            "        ControlSend, , !n                                                                                                                             "
            "        WinWaitClose                                                                                                                                  "
            "        forcefullyKillAcad()                                                                                                                          "
            "                                                                                                                                                      "
            "        ; I am including the force killing of autocad here because I suspect                                                                          "
            "        ; that it may be necessary to work around the powershell script's                                                                             "
            "        ; tendency to, when the powershell script goes to `"wait-process`" or                                                                         "
            "        ; doing Start-Process with the -Wait flag, which I think tries to wait                                                                        "
            "        ; for the process and all of its descendents to die, autocad's fatal                                                                          "
            "        ; crash leaves descendents still running, which causes a race condition                                                                       "
            "        ; with powershell waiting indefinitely because the descendents (like                                                                          "
            "        ; acwebbrowser, among others) have not yet died (And will never die                                                                           "
            "        ; unlkess killed)                                                                                                                             "
            "        ;                                                                                                                                             "
            "        ; (due to a change I made in the way the powershell script waits (using                                                                       "
            "        ; `"wait-process`" instead of the -Wait flag to start-process), the forc                                                                      "
            "        ; killing of acad might no longer be necessary here (because I think that                                                                     "
            "        ; wait-process only waits for the process itself to die, not all of its                                                                       "
            "        ; descendents too, whereas the -Wait flag on Start-Process waits for the                                                                      "
            "        ; death of the process and all its descendents.  I could be confused                                                                          "
            "        ; about this whole interaction, but, empirically, it doesn't seem to                                                                          "
            "        ; hurt anything to perform a force-killing of acad here.                                                                                      "
            "                                                                                                                                                      "
            "    } else if WinExist(`"ahk_group projectwiseSavePromptWindowDefinition`") {                                                                         "
            "        writeToLog(`"slapping down projectwise save prompt popup`")                                                                                   "
            "        ControlSend, , !n                                                                                                                             "
            "    } else if WinExist(`"ahk_group drawingFileNotValidWindowDefinition`") {                                                                           "
            "        writeToLog(`"slapping down drawingFileNotValid popup`")                                                                                       "
            "        ControlSend, , {Enter}                                                                                                                        "
            "        WinWaitClose                                                                                                                                  "
            "        forcefullyKillAcad()                                                                                                                          "
            "    } else if WinExist(`"ahk_group openDrawingErrorsFoundWindowDefinition`") {                                                                        "
            "        writeToLog(`"slapping down openDrawingErrorsFound popup`")                                                                                    "
            "        ; ControlSend, , !n                                                                                                                           "
            "        ControlClick,No,                                                                                                                              "
            "                                                                                                                                                      "
            "        ; there are two types of slapdown cases: one where our slapping down                                                                          "
            "        ; will simply facilitate acad's inevitable death so we can cut our losses                                                                     "
            "        ; and mvoe on to the next file to be processed, and another where our slapping down                                                           "
            "        ; will goad autocad into continue with the processing.                                                                                        "
            "        ; this is noe of the latter.                                                                                                                  "
            "    } else if WinExist(`"ahk_group trialPromptWindowDefinition`") {                                                                                   "
            "        writeToLog(`"slapping down trialPrompt popup`")                                                                                               "
            "        WinClose                                                                                                                                      "
            "        WinWaitClose                                                                                                                                  "
            "    } else if WinExist(`"ahk_group drawingNotBelongToCurrentProjectWindowDefinition`") {                                                              "
            "        writeToLog(`"slapping down drawingNotBelongToCurrentProject popup`")                                                                          "
            "        ControlClick,OK,                                                                                                                              "
            "    } else if WinExist(`"ahk_group drawingRecoveryWindowDefinition`") {                                                                               "
            "        writeToLog(`"slapping down drawingRecovery popup`")                                                                                           "
            "        ControlClick,Close,                                                                                                                           "
            "    } else if WinExist(`"ahk_group revitInvalidSignatureWindowDefinition`") {                                                                         "
            "        writeToLog(`"slapping down revitInvalidSignature popup`")                                                                                     "
            "        ControlClick,Load,                                                                                                                            "
            "    } else if WinExist(`"ahk_group revitUnsignedAddinWindowDefinition`") {                                                                            "
            "        writeToLog(`"slapping down revitUnsignedAddin popup`")                                                                                        "
            "        ControlClick,Always Load,                                                                                                                     "
            "    } else if WinExist(`"ahk_group revitErrorReportWindowDefinition`") {                                                                              "
            "        writeToLog(`"slapping down revitErrorReport popup`")                                                                                          "
            "        writeToLog(`"forcefully killing senddmp.exe`")                                                                                                "
            "        Run, taskkill /t /f /im senddmp.exe, , Hide                                                                                                   "
            "        ; WinClose                                                                                                                                    "
            "    } else if WinExist(`"ahk_group fusion360ErrorReportWindowDefinition`") {                                                                              "
            "        writeToLog(`"slapping down fusion360ErrorReport popup`")                                                                                          "
            "        writeToLog(`"forcefully killing senddmp.exe`")                                                                                                "
            "        Run, taskkill /t /f /im senddmp.exe, , Hide                                                                                                   "
            "        ; WinClose                                                                                                                                    "
            "    } else if WinExist(`"ahk_group revitErrorReportCancelledWindowDefinition`") {                                                                     "
            "        writeToLog(`"slapping down revitErrorReportCancelled popup`")                                                                                 "
            "        ; WinClose                                                                                                                                    "
            "        ; ControlClick,OK,                                                                                                                            "
            "        writeToLog(`"forcefully killing senddmp.exe`")                                                                                                "
            "        Run, taskkill /t /f /im senddmp.exe, , Hide                                                                                                   "
            "                                                                                                                                                      "
            "        ; most of the time, we won't get here, because we are kill senddmp.exe immediately upon detecting                                             "
            "        ; revitErrorReportWindowDefinition, which should prevent us from getting here.  But if we do get here, the proper response nevertheless is to "
            "        ; kill senddmp.exe.                                                                                                                           "
            "                                                                                                                                                      "
            "                                                                                                                                                      "
            "        ; unfortunately, the revit error report window takes two actions to slap down                                                                 "
            "        ; -- once to attempt to close the window,                                                                                                     "
            "        ; this causes a second popup to appear saying `"Your error report was cancelled before it was submitted to Autodesk, and asking you to        "
            "        ; click OK.  Because of the WiniWaitClose below (which is generally a sound thing to do)                                                      "
            "        ; we wait endlessly for the error report popup to disappear before even looking for the errorReportCancelled popup.                           "
            "        ;Fortunately, the whole thing can be slapped down by killing senddmp.exe.                                                                     "
            "                                                                                                                                                      "
            "    } else if WinExist(`"ahk_group acadErrorReportWindowDefinition`") {                                                                               "
            "        writeToLog(`"slapping down acadErrorReport popup`")                                                                                           "
            "        writeToLog(`"forcefully killing senddmp.exe`")                                                                                                "
            "        Run, taskkill /t /f /im senddmp.exe, , Hide                                                                                                   "
            "    } else if WinExist(`"ahk_group acadSaveDrawing1WindowDefinition`") {                                                                              "
            "        writeToLog(`"slapping down acadSaveDrawing1 popup`")                                                                                          "
            "        ControlClick,No,                                                                                                                              "
            "    } else {                                                                                                                                          "
            "        writeToLog(`"`"                                                                                                                               "
            "            . `"encountered an unexpected condition: `"                                                                                               "
            "            . `"anyPopupWindowDefinition matches, `"                                                                                                  "
            "            . `"but none of the individual groups seem to match.  `")                                                                                 "
            "                                                                                                                                                      "
            "        ; In this case, it is likely that the triggering window still exists, because we have not attempted to slap it down                           "
            "        ; so continuing looping is probabaly going to immediately retriggerr, ad infinitum.                                                           "
            "        ; therefore we wait for the triggering window to disappear (which will probably require manual action to happen,                              "
            "        ; but at least we wont be looping away clogging the log).                                                                                     "
            "        WinWaitClose                                                                                                                                  "
            "    }                                                                                                                                                 "
            "                                                                                                                                                      "
            "    ; in fact, its probably not a bad idea to ALWAYS wait for the triggering window                                                                   "
            "    ; to close, because our whole goal is to slap down the window and make it close.                                                                  "
            "    ; the only reason that we might not want to do winwaitclose is if it were in                                                                      "
            "    ; some situations to perform the slapdown attempt multiple times to work.                                                                         "
            "    ; but those cases should probably be handled within the individual                                                                                "
            "    ; `"else if`" clauses above anyway.                                                                                                               "
            "                                                                                                                                                      "
            "    WinWaitClose                                                                                                                                      "
            "                                                                                                                                                      "
            "    Sleep, 500                                                                                                                                        "
            "    ; a bit of delay for good measure.                                                                                                                "
            "}                                                                                                                                                     "
            "                                                                                                                                                      "
            "writeToLog(message){                                                                                                                                  "
            # "    logFile:=`"$($pathOfTemporarySlapdownLogDirectory)/`" . A_ScriptName . `".log`"                                                                   "
            "    global logFile "
            "    timestampFormat:=`"yyyy/MM/dd HH:mm:ss`"                                                                                                          "
            "    FormatTime, now,,%timestampFormat%                                                                                                                "
            "    FileAppend, %now%: %A_ScriptName% : %message%``n,%logFile%                                                                                        "
            "}                                                                                                                                                     "
            "                                                                                                                                                      "
            "forcefullyKillAcad(){                                                                                                                                 "
            "    writeToLog(`"forcefully killing autocad`")                                                                                                        "
            "    Run, taskkill /t /f /im acad.exe, , Hide                                                                                                          "
            "    Run, taskkill /t /f /im acwebbrowser.exe, , Hide                                                                                                  "
            "}                                                                                                                                                     "
            "                                                                                                                                                      "
            "                                                                                                                                                      "
            "viewTheLog(){                                                                                                                                 "
            "    global logFile "
            "    writeToLog(`"viewing the log`")                                                                                                        "
            "    Run, notepad++ `"%logFile%`"                                                                                                     "
            "}                                                                                                                                                     "
            "                                                                                                                                                      "
            "                                                                                                                                                      "
        ) -join "`n"
    )
    Set-Content -NoNewLine -Encoding ascii -Path $pathOfPopupSlapdownScriptFile -Value $popupSlapdownScriptContent
    $popupSlapdownScriptProcess = Start-Process -FilePath $pathOfPopupSlapdownScriptFile -PassThru
}
